// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package recentmessage

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7985edb4DecodeGithubComJulezDevChatuinoTwitchRecentmessage(in *jlexer.Lexer, out *responseData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "messages":
			if in.IsNull() {
				in.Skip()
				out.Messages = nil
			} else {
				in.Delim('[')
				if out.Messages == nil {
					if !in.IsDelim(']') {
						out.Messages = make([]string, 0, 4)
					} else {
						out.Messages = []string{}
					}
				} else {
					out.Messages = (out.Messages)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.Messages = append(out.Messages, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "error":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Error = string(in.String())
			}
		case "error_code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ErrorCode = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7985edb4EncodeGithubComJulezDevChatuinoTwitchRecentmessage(out *jwriter.Writer, in responseData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"messages\":"
		out.RawString(prefix[1:])
		if in.Messages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Messages {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix)
		out.String(string(in.Error))
	}
	{
		const prefix string = ",\"error_code\":"
		out.RawString(prefix)
		out.String(string(in.ErrorCode))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v responseData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7985edb4EncodeGithubComJulezDevChatuinoTwitchRecentmessage(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v responseData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7985edb4EncodeGithubComJulezDevChatuinoTwitchRecentmessage(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *responseData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7985edb4DecodeGithubComJulezDevChatuinoTwitchRecentmessage(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *responseData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7985edb4DecodeGithubComJulezDevChatuinoTwitchRecentmessage(l, v)
}
