// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package kittyimg

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA7e4ce3aDecodeGithubComJulezDevChatuinoKittyimg(in *jlexer.Lexer, out *DecodedImageFrame) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "width":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Width = int(in.Int())
			}
		case "height":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Height = int(in.Int())
			}
		case "encoded_path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EncodedPath = string(in.String())
			}
		case "delay_in_ms":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DelayInMS = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA7e4ce3aEncodeGithubComJulezDevChatuinoKittyimg(out *jwriter.Writer, in DecodedImageFrame) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"width\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Width))
	}
	{
		const prefix string = ",\"height\":"
		out.RawString(prefix)
		out.Int(int(in.Height))
	}
	{
		const prefix string = ",\"encoded_path\":"
		out.RawString(prefix)
		out.String(string(in.EncodedPath))
	}
	{
		const prefix string = ",\"delay_in_ms\":"
		out.RawString(prefix)
		out.Int(int(in.DelayInMS))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DecodedImageFrame) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA7e4ce3aEncodeGithubComJulezDevChatuinoKittyimg(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DecodedImageFrame) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA7e4ce3aDecodeGithubComJulezDevChatuinoKittyimg(l, v)
}
func easyjsonA7e4ce3aDecodeGithubComJulezDevChatuinoKittyimg1(in *jlexer.Lexer, out *DecodedImage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "cols":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cols = int(in.Int())
			}
		case "images":
			if in.IsNull() {
				in.Skip()
				out.Images = nil
			} else {
				in.Delim('[')
				if out.Images == nil {
					if !in.IsDelim(']') {
						out.Images = make([]DecodedImageFrame, 0, 1)
					} else {
						out.Images = []DecodedImageFrame{}
					}
				} else {
					out.Images = (out.Images)[:0]
				}
				for !in.IsDelim(']') {
					var v1 DecodedImageFrame
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Images = append(out.Images, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA7e4ce3aEncodeGithubComJulezDevChatuinoKittyimg1(out *jwriter.Writer, in DecodedImage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"cols\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Cols))
	}
	{
		const prefix string = ",\"images\":"
		out.RawString(prefix)
		if in.Images == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Images {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DecodedImage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA7e4ce3aEncodeGithubComJulezDevChatuinoKittyimg1(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DecodedImage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA7e4ce3aDecodeGithubComJulezDevChatuinoKittyimg1(l, v)
}
