// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/julez-dev/chatuino/twitch/twitchapi"
	"github.com/julez-dev/chatuino/twitch/twitchirc"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBadgeCache creates a new instance of MockBadgeCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBadgeCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBadgeCache {
	mock := &MockBadgeCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBadgeCache is an autogenerated mock type for the BadgeCache type
type MockBadgeCache struct {
	mock.Mock
}

type MockBadgeCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBadgeCache) EXPECT() *MockBadgeCache_Expecter {
	return &MockBadgeCache_Expecter{mock: &_m.Mock}
}

// MatchBadgeSet provides a mock function for the type MockBadgeCache
func (_mock *MockBadgeCache) MatchBadgeSet(broadcasterID string, ircBadge []twitchirc.Badge) map[string]twitchapi.BadgeVersion {
	ret := _mock.Called(broadcasterID, ircBadge)

	if len(ret) == 0 {
		panic("no return value specified for MatchBadgeSet")
	}

	var r0 map[string]twitchapi.BadgeVersion
	if returnFunc, ok := ret.Get(0).(func(string, []twitchirc.Badge) map[string]twitchapi.BadgeVersion); ok {
		r0 = returnFunc(broadcasterID, ircBadge)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]twitchapi.BadgeVersion)
		}
	}
	return r0
}

// MockBadgeCache_MatchBadgeSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MatchBadgeSet'
type MockBadgeCache_MatchBadgeSet_Call struct {
	*mock.Call
}

// MatchBadgeSet is a helper method to define mock.On call
//   - broadcasterID string
//   - ircBadge []twitchirc.Badge
func (_e *MockBadgeCache_Expecter) MatchBadgeSet(broadcasterID interface{}, ircBadge interface{}) *MockBadgeCache_MatchBadgeSet_Call {
	return &MockBadgeCache_MatchBadgeSet_Call{Call: _e.mock.On("MatchBadgeSet", broadcasterID, ircBadge)}
}

func (_c *MockBadgeCache_MatchBadgeSet_Call) Run(run func(broadcasterID string, ircBadge []twitchirc.Badge)) *MockBadgeCache_MatchBadgeSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []twitchirc.Badge
		if args[1] != nil {
			arg1 = args[1].([]twitchirc.Badge)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBadgeCache_MatchBadgeSet_Call) Return(stringToBadgeVersion map[string]twitchapi.BadgeVersion) *MockBadgeCache_MatchBadgeSet_Call {
	_c.Call.Return(stringToBadgeVersion)
	return _c
}

func (_c *MockBadgeCache_MatchBadgeSet_Call) RunAndReturn(run func(broadcasterID string, ircBadge []twitchirc.Badge) map[string]twitchapi.BadgeVersion) *MockBadgeCache_MatchBadgeSet_Call {
	_c.Call.Return(run)
	return _c
}
