// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	twitchapi "github.com/julez-dev/chatuino/twitch/twitchapi"
	twitchirc "github.com/julez-dev/chatuino/twitch/twitchirc"
	mock "github.com/stretchr/testify/mock"
)

// BadgeCache is an autogenerated mock type for the BadgeCache type
type BadgeCache struct {
	mock.Mock
}

type BadgeCache_Expecter struct {
	mock *mock.Mock
}

func (_m *BadgeCache) EXPECT() *BadgeCache_Expecter {
	return &BadgeCache_Expecter{mock: &_m.Mock}
}

// MatchBadgeSet provides a mock function with given fields: broadcasterID, ircBadge
func (_m *BadgeCache) MatchBadgeSet(broadcasterID string, ircBadge []twitchirc.Badge) map[string]twitchapi.BadgeVersion {
	ret := _m.Called(broadcasterID, ircBadge)

	if len(ret) == 0 {
		panic("no return value specified for MatchBadgeSet")
	}

	var r0 map[string]twitchapi.BadgeVersion
	if rf, ok := ret.Get(0).(func(string, []twitchirc.Badge) map[string]twitchapi.BadgeVersion); ok {
		r0 = rf(broadcasterID, ircBadge)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]twitchapi.BadgeVersion)
		}
	}

	return r0
}

// BadgeCache_MatchBadgeSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MatchBadgeSet'
type BadgeCache_MatchBadgeSet_Call struct {
	*mock.Call
}

// MatchBadgeSet is a helper method to define mock.On call
//   - broadcasterID string
//   - ircBadge []twitchirc.Badge
func (_e *BadgeCache_Expecter) MatchBadgeSet(broadcasterID interface{}, ircBadge interface{}) *BadgeCache_MatchBadgeSet_Call {
	return &BadgeCache_MatchBadgeSet_Call{Call: _e.mock.On("MatchBadgeSet", broadcasterID, ircBadge)}
}

func (_c *BadgeCache_MatchBadgeSet_Call) Run(run func(broadcasterID string, ircBadge []twitchirc.Badge)) *BadgeCache_MatchBadgeSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]twitchirc.Badge))
	})
	return _c
}

func (_c *BadgeCache_MatchBadgeSet_Call) Return(_a0 map[string]twitchapi.BadgeVersion) *BadgeCache_MatchBadgeSet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BadgeCache_MatchBadgeSet_Call) RunAndReturn(run func(string, []twitchirc.Badge) map[string]twitchapi.BadgeVersion) *BadgeCache_MatchBadgeSet_Call {
	_c.Call.Return(run)
	return _c
}

// NewBadgeCache creates a new instance of BadgeCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBadgeCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *BadgeCache {
	mock := &BadgeCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
