// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	twitchapi "github.com/julez-dev/chatuino/twitch/twitchapi"
	mock "github.com/stretchr/testify/mock"
)

// BadgeFetcher is an autogenerated mock type for the BadgeFetcher type
type BadgeFetcher struct {
	mock.Mock
}

type BadgeFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *BadgeFetcher) EXPECT() *BadgeFetcher_Expecter {
	return &BadgeFetcher_Expecter{mock: &_m.Mock}
}

// GetChannelChatBadges provides a mock function with given fields: ctx, broadcasterID
func (_m *BadgeFetcher) GetChannelChatBadges(ctx context.Context, broadcasterID string) ([]twitchapi.BadgeSet, error) {
	ret := _m.Called(ctx, broadcasterID)

	if len(ret) == 0 {
		panic("no return value specified for GetChannelChatBadges")
	}

	var r0 []twitchapi.BadgeSet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]twitchapi.BadgeSet, error)); ok {
		return rf(ctx, broadcasterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []twitchapi.BadgeSet); ok {
		r0 = rf(ctx, broadcasterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]twitchapi.BadgeSet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, broadcasterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BadgeFetcher_GetChannelChatBadges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannelChatBadges'
type BadgeFetcher_GetChannelChatBadges_Call struct {
	*mock.Call
}

// GetChannelChatBadges is a helper method to define mock.On call
//   - ctx context.Context
//   - broadcasterID string
func (_e *BadgeFetcher_Expecter) GetChannelChatBadges(ctx interface{}, broadcasterID interface{}) *BadgeFetcher_GetChannelChatBadges_Call {
	return &BadgeFetcher_GetChannelChatBadges_Call{Call: _e.mock.On("GetChannelChatBadges", ctx, broadcasterID)}
}

func (_c *BadgeFetcher_GetChannelChatBadges_Call) Run(run func(ctx context.Context, broadcasterID string)) *BadgeFetcher_GetChannelChatBadges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BadgeFetcher_GetChannelChatBadges_Call) Return(_a0 []twitchapi.BadgeSet, _a1 error) *BadgeFetcher_GetChannelChatBadges_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BadgeFetcher_GetChannelChatBadges_Call) RunAndReturn(run func(context.Context, string) ([]twitchapi.BadgeSet, error)) *BadgeFetcher_GetChannelChatBadges_Call {
	_c.Call.Return(run)
	return _c
}

// GetGlobalChatBadges provides a mock function with given fields: ctx
func (_m *BadgeFetcher) GetGlobalChatBadges(ctx context.Context) ([]twitchapi.BadgeSet, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGlobalChatBadges")
	}

	var r0 []twitchapi.BadgeSet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]twitchapi.BadgeSet, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []twitchapi.BadgeSet); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]twitchapi.BadgeSet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BadgeFetcher_GetGlobalChatBadges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGlobalChatBadges'
type BadgeFetcher_GetGlobalChatBadges_Call struct {
	*mock.Call
}

// GetGlobalChatBadges is a helper method to define mock.On call
//   - ctx context.Context
func (_e *BadgeFetcher_Expecter) GetGlobalChatBadges(ctx interface{}) *BadgeFetcher_GetGlobalChatBadges_Call {
	return &BadgeFetcher_GetGlobalChatBadges_Call{Call: _e.mock.On("GetGlobalChatBadges", ctx)}
}

func (_c *BadgeFetcher_GetGlobalChatBadges_Call) Run(run func(ctx context.Context)) *BadgeFetcher_GetGlobalChatBadges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *BadgeFetcher_GetGlobalChatBadges_Call) Return(_a0 []twitchapi.BadgeSet, _a1 error) *BadgeFetcher_GetGlobalChatBadges_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BadgeFetcher_GetGlobalChatBadges_Call) RunAndReturn(run func(context.Context) ([]twitchapi.BadgeSet, error)) *BadgeFetcher_GetGlobalChatBadges_Call {
	_c.Call.Return(run)
	return _c
}

// NewBadgeFetcher creates a new instance of BadgeFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBadgeFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *BadgeFetcher {
	mock := &BadgeFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
