// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/julez-dev/chatuino/twitch/twitchapi"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBadgeFetcher creates a new instance of MockBadgeFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBadgeFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBadgeFetcher {
	mock := &MockBadgeFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBadgeFetcher is an autogenerated mock type for the BadgeFetcher type
type MockBadgeFetcher struct {
	mock.Mock
}

type MockBadgeFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBadgeFetcher) EXPECT() *MockBadgeFetcher_Expecter {
	return &MockBadgeFetcher_Expecter{mock: &_m.Mock}
}

// GetChannelChatBadges provides a mock function for the type MockBadgeFetcher
func (_mock *MockBadgeFetcher) GetChannelChatBadges(ctx context.Context, broadcasterID string) ([]twitchapi.BadgeSet, error) {
	ret := _mock.Called(ctx, broadcasterID)

	if len(ret) == 0 {
		panic("no return value specified for GetChannelChatBadges")
	}

	var r0 []twitchapi.BadgeSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]twitchapi.BadgeSet, error)); ok {
		return returnFunc(ctx, broadcasterID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []twitchapi.BadgeSet); ok {
		r0 = returnFunc(ctx, broadcasterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]twitchapi.BadgeSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, broadcasterID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBadgeFetcher_GetChannelChatBadges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannelChatBadges'
type MockBadgeFetcher_GetChannelChatBadges_Call struct {
	*mock.Call
}

// GetChannelChatBadges is a helper method to define mock.On call
//   - ctx context.Context
//   - broadcasterID string
func (_e *MockBadgeFetcher_Expecter) GetChannelChatBadges(ctx interface{}, broadcasterID interface{}) *MockBadgeFetcher_GetChannelChatBadges_Call {
	return &MockBadgeFetcher_GetChannelChatBadges_Call{Call: _e.mock.On("GetChannelChatBadges", ctx, broadcasterID)}
}

func (_c *MockBadgeFetcher_GetChannelChatBadges_Call) Run(run func(ctx context.Context, broadcasterID string)) *MockBadgeFetcher_GetChannelChatBadges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBadgeFetcher_GetChannelChatBadges_Call) Return(badgeSets []twitchapi.BadgeSet, err error) *MockBadgeFetcher_GetChannelChatBadges_Call {
	_c.Call.Return(badgeSets, err)
	return _c
}

func (_c *MockBadgeFetcher_GetChannelChatBadges_Call) RunAndReturn(run func(ctx context.Context, broadcasterID string) ([]twitchapi.BadgeSet, error)) *MockBadgeFetcher_GetChannelChatBadges_Call {
	_c.Call.Return(run)
	return _c
}

// GetGlobalChatBadges provides a mock function for the type MockBadgeFetcher
func (_mock *MockBadgeFetcher) GetGlobalChatBadges(ctx context.Context) ([]twitchapi.BadgeSet, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGlobalChatBadges")
	}

	var r0 []twitchapi.BadgeSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]twitchapi.BadgeSet, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []twitchapi.BadgeSet); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]twitchapi.BadgeSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBadgeFetcher_GetGlobalChatBadges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGlobalChatBadges'
type MockBadgeFetcher_GetGlobalChatBadges_Call struct {
	*mock.Call
}

// GetGlobalChatBadges is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBadgeFetcher_Expecter) GetGlobalChatBadges(ctx interface{}) *MockBadgeFetcher_GetGlobalChatBadges_Call {
	return &MockBadgeFetcher_GetGlobalChatBadges_Call{Call: _e.mock.On("GetGlobalChatBadges", ctx)}
}

func (_c *MockBadgeFetcher_GetGlobalChatBadges_Call) Run(run func(ctx context.Context)) *MockBadgeFetcher_GetGlobalChatBadges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBadgeFetcher_GetGlobalChatBadges_Call) Return(badgeSets []twitchapi.BadgeSet, err error) *MockBadgeFetcher_GetGlobalChatBadges_Call {
	_c.Call.Return(badgeSets, err)
	return _c
}

func (_c *MockBadgeFetcher_GetGlobalChatBadges_Call) RunAndReturn(run func(ctx context.Context) ([]twitchapi.BadgeSet, error)) *MockBadgeFetcher_GetGlobalChatBadges_Call {
	_c.Call.Return(run)
	return _c
}
