// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	bttv "github.com/julez-dev/chatuino/twitch/bttv"

	mock "github.com/stretchr/testify/mock"
)

// MockBTTVEmoteFetcher is an autogenerated mock type for the BTTVEmoteFetcher type
type MockBTTVEmoteFetcher struct {
	mock.Mock
}

type MockBTTVEmoteFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBTTVEmoteFetcher) EXPECT() *MockBTTVEmoteFetcher_Expecter {
	return &MockBTTVEmoteFetcher_Expecter{mock: &_m.Mock}
}

// GetChannelEmotes provides a mock function with given fields: ctx, broadcaster
func (_m *MockBTTVEmoteFetcher) GetChannelEmotes(ctx context.Context, broadcaster string) (bttv.UserResponse, error) {
	ret := _m.Called(ctx, broadcaster)

	if len(ret) == 0 {
		panic("no return value specified for GetChannelEmotes")
	}

	var r0 bttv.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bttv.UserResponse, error)); ok {
		return rf(ctx, broadcaster)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bttv.UserResponse); ok {
		r0 = rf(ctx, broadcaster)
	} else {
		r0 = ret.Get(0).(bttv.UserResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, broadcaster)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBTTVEmoteFetcher_GetChannelEmotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannelEmotes'
type MockBTTVEmoteFetcher_GetChannelEmotes_Call struct {
	*mock.Call
}

// GetChannelEmotes is a helper method to define mock.On call
//   - ctx context.Context
//   - broadcaster string
func (_e *MockBTTVEmoteFetcher_Expecter) GetChannelEmotes(ctx interface{}, broadcaster interface{}) *MockBTTVEmoteFetcher_GetChannelEmotes_Call {
	return &MockBTTVEmoteFetcher_GetChannelEmotes_Call{Call: _e.mock.On("GetChannelEmotes", ctx, broadcaster)}
}

func (_c *MockBTTVEmoteFetcher_GetChannelEmotes_Call) Run(run func(ctx context.Context, broadcaster string)) *MockBTTVEmoteFetcher_GetChannelEmotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBTTVEmoteFetcher_GetChannelEmotes_Call) Return(_a0 bttv.UserResponse, _a1 error) *MockBTTVEmoteFetcher_GetChannelEmotes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBTTVEmoteFetcher_GetChannelEmotes_Call) RunAndReturn(run func(context.Context, string) (bttv.UserResponse, error)) *MockBTTVEmoteFetcher_GetChannelEmotes_Call {
	_c.Call.Return(run)
	return _c
}

// GetGlobalEmotes provides a mock function with given fields: _a0
func (_m *MockBTTVEmoteFetcher) GetGlobalEmotes(_a0 context.Context) (bttv.GlobalEmoteResponse, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetGlobalEmotes")
	}

	var r0 bttv.GlobalEmoteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bttv.GlobalEmoteResponse, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bttv.GlobalEmoteResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bttv.GlobalEmoteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBTTVEmoteFetcher_GetGlobalEmotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGlobalEmotes'
type MockBTTVEmoteFetcher_GetGlobalEmotes_Call struct {
	*mock.Call
}

// GetGlobalEmotes is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockBTTVEmoteFetcher_Expecter) GetGlobalEmotes(_a0 interface{}) *MockBTTVEmoteFetcher_GetGlobalEmotes_Call {
	return &MockBTTVEmoteFetcher_GetGlobalEmotes_Call{Call: _e.mock.On("GetGlobalEmotes", _a0)}
}

func (_c *MockBTTVEmoteFetcher_GetGlobalEmotes_Call) Run(run func(_a0 context.Context)) *MockBTTVEmoteFetcher_GetGlobalEmotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockBTTVEmoteFetcher_GetGlobalEmotes_Call) Return(_a0 bttv.GlobalEmoteResponse, _a1 error) *MockBTTVEmoteFetcher_GetGlobalEmotes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBTTVEmoteFetcher_GetGlobalEmotes_Call) RunAndReturn(run func(context.Context) (bttv.GlobalEmoteResponse, error)) *MockBTTVEmoteFetcher_GetGlobalEmotes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBTTVEmoteFetcher creates a new instance of MockBTTVEmoteFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBTTVEmoteFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBTTVEmoteFetcher {
	mock := &MockBTTVEmoteFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
