// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/julez-dev/chatuino/twitch/bttv"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBTTVEmoteFetcher creates a new instance of MockBTTVEmoteFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBTTVEmoteFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBTTVEmoteFetcher {
	mock := &MockBTTVEmoteFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBTTVEmoteFetcher is an autogenerated mock type for the BTTVEmoteFetcher type
type MockBTTVEmoteFetcher struct {
	mock.Mock
}

type MockBTTVEmoteFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBTTVEmoteFetcher) EXPECT() *MockBTTVEmoteFetcher_Expecter {
	return &MockBTTVEmoteFetcher_Expecter{mock: &_m.Mock}
}

// GetChannelEmotes provides a mock function for the type MockBTTVEmoteFetcher
func (_mock *MockBTTVEmoteFetcher) GetChannelEmotes(ctx context.Context, broadcaster string) (bttv.UserResponse, error) {
	ret := _mock.Called(ctx, broadcaster)

	if len(ret) == 0 {
		panic("no return value specified for GetChannelEmotes")
	}

	var r0 bttv.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bttv.UserResponse, error)); ok {
		return returnFunc(ctx, broadcaster)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bttv.UserResponse); ok {
		r0 = returnFunc(ctx, broadcaster)
	} else {
		r0 = ret.Get(0).(bttv.UserResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, broadcaster)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBTTVEmoteFetcher_GetChannelEmotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannelEmotes'
type MockBTTVEmoteFetcher_GetChannelEmotes_Call struct {
	*mock.Call
}

// GetChannelEmotes is a helper method to define mock.On call
//   - ctx context.Context
//   - broadcaster string
func (_e *MockBTTVEmoteFetcher_Expecter) GetChannelEmotes(ctx interface{}, broadcaster interface{}) *MockBTTVEmoteFetcher_GetChannelEmotes_Call {
	return &MockBTTVEmoteFetcher_GetChannelEmotes_Call{Call: _e.mock.On("GetChannelEmotes", ctx, broadcaster)}
}

func (_c *MockBTTVEmoteFetcher_GetChannelEmotes_Call) Run(run func(ctx context.Context, broadcaster string)) *MockBTTVEmoteFetcher_GetChannelEmotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBTTVEmoteFetcher_GetChannelEmotes_Call) Return(userResponse bttv.UserResponse, err error) *MockBTTVEmoteFetcher_GetChannelEmotes_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockBTTVEmoteFetcher_GetChannelEmotes_Call) RunAndReturn(run func(ctx context.Context, broadcaster string) (bttv.UserResponse, error)) *MockBTTVEmoteFetcher_GetChannelEmotes_Call {
	_c.Call.Return(run)
	return _c
}

// GetGlobalEmotes provides a mock function for the type MockBTTVEmoteFetcher
func (_mock *MockBTTVEmoteFetcher) GetGlobalEmotes(context1 context.Context) (bttv.GlobalEmoteResponse, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetGlobalEmotes")
	}

	var r0 bttv.GlobalEmoteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (bttv.GlobalEmoteResponse, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) bttv.GlobalEmoteResponse); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bttv.GlobalEmoteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBTTVEmoteFetcher_GetGlobalEmotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGlobalEmotes'
type MockBTTVEmoteFetcher_GetGlobalEmotes_Call struct {
	*mock.Call
}

// GetGlobalEmotes is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockBTTVEmoteFetcher_Expecter) GetGlobalEmotes(context1 interface{}) *MockBTTVEmoteFetcher_GetGlobalEmotes_Call {
	return &MockBTTVEmoteFetcher_GetGlobalEmotes_Call{Call: _e.mock.On("GetGlobalEmotes", context1)}
}

func (_c *MockBTTVEmoteFetcher_GetGlobalEmotes_Call) Run(run func(context1 context.Context)) *MockBTTVEmoteFetcher_GetGlobalEmotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBTTVEmoteFetcher_GetGlobalEmotes_Call) Return(globalEmoteResponse bttv.GlobalEmoteResponse, err error) *MockBTTVEmoteFetcher_GetGlobalEmotes_Call {
	_c.Call.Return(globalEmoteResponse, err)
	return _c
}

func (_c *MockBTTVEmoteFetcher_GetGlobalEmotes_Call) RunAndReturn(run func(context1 context.Context) (bttv.GlobalEmoteResponse, error)) *MockBTTVEmoteFetcher_GetGlobalEmotes_Call {
	_c.Call.Return(run)
	return _c
}
