// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"database/sql"

	mock "github.com/stretchr/testify/mock"
)

// NewDBVariadic creates a new instance of DBVariadic. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDBVariadic(t interface {
	mock.TestingT
	Cleanup(func())
}) *DBVariadic {
	mock := &DBVariadic{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DBVariadic is an autogenerated mock type for the DB type
type DBVariadic struct {
	mock.Mock
}

type DBVariadic_Expecter struct {
	mock *mock.Mock
}

func (_m *DBVariadic) EXPECT() *DBVariadic_Expecter {
	return &DBVariadic_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type DBVariadic
func (_mock *DBVariadic) Exec(query string, args ...any) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 sql.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...any) (sql.Result, error)); ok {
		return returnFunc(query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...any) sql.Result); ok {
		r0 = returnFunc(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...any) error); ok {
		r1 = returnFunc(query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DBVariadic_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type DBVariadic_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - query string
//   - args ...any
func (_e *DBVariadic_Expecter) Exec(query interface{}, args ...interface{}) *DBVariadic_Exec_Call {
	return &DBVariadic_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{query}, args...)...)}
}

func (_c *DBVariadic_Exec_Call) Run(run func(query string, args ...any)) *DBVariadic_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *DBVariadic_Exec_Call) Return(result sql.Result, err error) *DBVariadic_Exec_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *DBVariadic_Exec_Call) RunAndReturn(run func(query string, args ...any) (sql.Result, error)) *DBVariadic_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type DBVariadic
func (_mock *DBVariadic) Query(query string, args ...any) (*sql.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *sql.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...any) (*sql.Rows, error)); ok {
		return returnFunc(query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...any) *sql.Rows); ok {
		r0 = returnFunc(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...any) error); ok {
		r1 = returnFunc(query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DBVariadic_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type DBVariadic_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - query string
//   - args ...any
func (_e *DBVariadic_Expecter) Query(query interface{}, args ...interface{}) *DBVariadic_Query_Call {
	return &DBVariadic_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{query}, args...)...)}
}

func (_c *DBVariadic_Query_Call) Run(run func(query string, args ...any)) *DBVariadic_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *DBVariadic_Query_Call) Return(rows *sql.Rows, err error) *DBVariadic_Query_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *DBVariadic_Query_Call) RunAndReturn(run func(query string, args ...any) (*sql.Rows, error)) *DBVariadic_Query_Call {
	_c.Call.Return(run)
	return _c
}
