// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/julez-dev/chatuino/kittyimg"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDisplayManager creates a new instance of MockDisplayManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDisplayManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDisplayManager {
	mock := &MockDisplayManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDisplayManager is an autogenerated mock type for the DisplayManager type
type MockDisplayManager struct {
	mock.Mock
}

type MockDisplayManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDisplayManager) EXPECT() *MockDisplayManager_Expecter {
	return &MockDisplayManager_Expecter{mock: &_m.Mock}
}

// Convert provides a mock function for the type MockDisplayManager
func (_mock *MockDisplayManager) Convert(unit kittyimg.DisplayUnit) (kittyimg.KittyDisplayUnit, error) {
	ret := _mock.Called(unit)

	if len(ret) == 0 {
		panic("no return value specified for Convert")
	}

	var r0 kittyimg.KittyDisplayUnit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(kittyimg.DisplayUnit) (kittyimg.KittyDisplayUnit, error)); ok {
		return returnFunc(unit)
	}
	if returnFunc, ok := ret.Get(0).(func(kittyimg.DisplayUnit) kittyimg.KittyDisplayUnit); ok {
		r0 = returnFunc(unit)
	} else {
		r0 = ret.Get(0).(kittyimg.KittyDisplayUnit)
	}
	if returnFunc, ok := ret.Get(1).(func(kittyimg.DisplayUnit) error); ok {
		r1 = returnFunc(unit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDisplayManager_Convert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Convert'
type MockDisplayManager_Convert_Call struct {
	*mock.Call
}

// Convert is a helper method to define mock.On call
//   - unit kittyimg.DisplayUnit
func (_e *MockDisplayManager_Expecter) Convert(unit interface{}) *MockDisplayManager_Convert_Call {
	return &MockDisplayManager_Convert_Call{Call: _e.mock.On("Convert", unit)}
}

func (_c *MockDisplayManager_Convert_Call) Run(run func(unit kittyimg.DisplayUnit)) *MockDisplayManager_Convert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 kittyimg.DisplayUnit
		if args[0] != nil {
			arg0 = args[0].(kittyimg.DisplayUnit)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDisplayManager_Convert_Call) Return(kittyDisplayUnit kittyimg.KittyDisplayUnit, err error) *MockDisplayManager_Convert_Call {
	_c.Call.Return(kittyDisplayUnit, err)
	return _c
}

func (_c *MockDisplayManager_Convert_Call) RunAndReturn(run func(unit kittyimg.DisplayUnit) (kittyimg.KittyDisplayUnit, error)) *MockDisplayManager_Convert_Call {
	_c.Call.Return(run)
	return _c
}
