// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	kittyimg "github.com/julez-dev/chatuino/kittyimg"
	mock "github.com/stretchr/testify/mock"
)

// DisplayManager is an autogenerated mock type for the DisplayManager type
type DisplayManager struct {
	mock.Mock
}

type DisplayManager_Expecter struct {
	mock *mock.Mock
}

func (_m *DisplayManager) EXPECT() *DisplayManager_Expecter {
	return &DisplayManager_Expecter{mock: &_m.Mock}
}

// Convert provides a mock function with given fields: unit
func (_m *DisplayManager) Convert(unit kittyimg.DisplayUnit) (kittyimg.KittyDisplayUnit, error) {
	ret := _m.Called(unit)

	if len(ret) == 0 {
		panic("no return value specified for Convert")
	}

	var r0 kittyimg.KittyDisplayUnit
	var r1 error
	if rf, ok := ret.Get(0).(func(kittyimg.DisplayUnit) (kittyimg.KittyDisplayUnit, error)); ok {
		return rf(unit)
	}
	if rf, ok := ret.Get(0).(func(kittyimg.DisplayUnit) kittyimg.KittyDisplayUnit); ok {
		r0 = rf(unit)
	} else {
		r0 = ret.Get(0).(kittyimg.KittyDisplayUnit)
	}

	if rf, ok := ret.Get(1).(func(kittyimg.DisplayUnit) error); ok {
		r1 = rf(unit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DisplayManager_Convert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Convert'
type DisplayManager_Convert_Call struct {
	*mock.Call
}

// Convert is a helper method to define mock.On call
//   - unit kittyimg.DisplayUnit
func (_e *DisplayManager_Expecter) Convert(unit interface{}) *DisplayManager_Convert_Call {
	return &DisplayManager_Convert_Call{Call: _e.mock.On("Convert", unit)}
}

func (_c *DisplayManager_Convert_Call) Run(run func(unit kittyimg.DisplayUnit)) *DisplayManager_Convert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(kittyimg.DisplayUnit))
	})
	return _c
}

func (_c *DisplayManager_Convert_Call) Return(_a0 kittyimg.KittyDisplayUnit, _a1 error) *DisplayManager_Convert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DisplayManager_Convert_Call) RunAndReturn(run func(kittyimg.DisplayUnit) (kittyimg.KittyDisplayUnit, error)) *DisplayManager_Convert_Call {
	_c.Call.Return(run)
	return _c
}

// NewDisplayManager creates a new instance of DisplayManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDisplayManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *DisplayManager {
	mock := &DisplayManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
