// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/julez-dev/chatuino/emote"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEmoteStore creates a new instance of MockEmoteStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmoteStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmoteStore {
	mock := &MockEmoteStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmoteStore is an autogenerated mock type for the EmoteStore type
type MockEmoteStore struct {
	mock.Mock
}

type MockEmoteStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmoteStore) EXPECT() *MockEmoteStore_Expecter {
	return &MockEmoteStore_Expecter{mock: &_m.Mock}
}

// GetByText provides a mock function for the type MockEmoteStore
func (_mock *MockEmoteStore) GetByText(channelID string, text string) (emote.Emote, bool) {
	ret := _mock.Called(channelID, text)

	if len(ret) == 0 {
		panic("no return value specified for GetByText")
	}

	var r0 emote.Emote
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) (emote.Emote, bool)); ok {
		return returnFunc(channelID, text)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) emote.Emote); ok {
		r0 = returnFunc(channelID, text)
	} else {
		r0 = ret.Get(0).(emote.Emote)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) bool); ok {
		r1 = returnFunc(channelID, text)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockEmoteStore_GetByText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByText'
type MockEmoteStore_GetByText_Call struct {
	*mock.Call
}

// GetByText is a helper method to define mock.On call
//   - channelID string
//   - text string
func (_e *MockEmoteStore_Expecter) GetByText(channelID interface{}, text interface{}) *MockEmoteStore_GetByText_Call {
	return &MockEmoteStore_GetByText_Call{Call: _e.mock.On("GetByText", channelID, text)}
}

func (_c *MockEmoteStore_GetByText_Call) Run(run func(channelID string, text string)) *MockEmoteStore_GetByText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmoteStore_GetByText_Call) Return(emote1 emote.Emote, b bool) *MockEmoteStore_GetByText_Call {
	_c.Call.Return(emote1, b)
	return _c
}

func (_c *MockEmoteStore_GetByText_Call) RunAndReturn(run func(channelID string, text string) (emote.Emote, bool)) *MockEmoteStore_GetByText_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTextAllChannels provides a mock function for the type MockEmoteStore
func (_mock *MockEmoteStore) GetByTextAllChannels(text string) (emote.Emote, bool) {
	ret := _mock.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for GetByTextAllChannels")
	}

	var r0 emote.Emote
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (emote.Emote, bool)); ok {
		return returnFunc(text)
	}
	if returnFunc, ok := ret.Get(0).(func(string) emote.Emote); ok {
		r0 = returnFunc(text)
	} else {
		r0 = ret.Get(0).(emote.Emote)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(text)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockEmoteStore_GetByTextAllChannels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTextAllChannels'
type MockEmoteStore_GetByTextAllChannels_Call struct {
	*mock.Call
}

// GetByTextAllChannels is a helper method to define mock.On call
//   - text string
func (_e *MockEmoteStore_Expecter) GetByTextAllChannels(text interface{}) *MockEmoteStore_GetByTextAllChannels_Call {
	return &MockEmoteStore_GetByTextAllChannels_Call{Call: _e.mock.On("GetByTextAllChannels", text)}
}

func (_c *MockEmoteStore_GetByTextAllChannels_Call) Run(run func(text string)) *MockEmoteStore_GetByTextAllChannels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEmoteStore_GetByTextAllChannels_Call) Return(emote1 emote.Emote, b bool) *MockEmoteStore_GetByTextAllChannels_Call {
	_c.Call.Return(emote1, b)
	return _c
}

func (_c *MockEmoteStore_GetByTextAllChannels_Call) RunAndReturn(run func(text string) (emote.Emote, bool)) *MockEmoteStore_GetByTextAllChannels_Call {
	_c.Call.Return(run)
	return _c
}

// LoadSetForeignEmote provides a mock function for the type MockEmoteStore
func (_mock *MockEmoteStore) LoadSetForeignEmote(emoteID string, emoteText string) emote.Emote {
	ret := _mock.Called(emoteID, emoteText)

	if len(ret) == 0 {
		panic("no return value specified for LoadSetForeignEmote")
	}

	var r0 emote.Emote
	if returnFunc, ok := ret.Get(0).(func(string, string) emote.Emote); ok {
		r0 = returnFunc(emoteID, emoteText)
	} else {
		r0 = ret.Get(0).(emote.Emote)
	}
	return r0
}

// MockEmoteStore_LoadSetForeignEmote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadSetForeignEmote'
type MockEmoteStore_LoadSetForeignEmote_Call struct {
	*mock.Call
}

// LoadSetForeignEmote is a helper method to define mock.On call
//   - emoteID string
//   - emoteText string
func (_e *MockEmoteStore_Expecter) LoadSetForeignEmote(emoteID interface{}, emoteText interface{}) *MockEmoteStore_LoadSetForeignEmote_Call {
	return &MockEmoteStore_LoadSetForeignEmote_Call{Call: _e.mock.On("LoadSetForeignEmote", emoteID, emoteText)}
}

func (_c *MockEmoteStore_LoadSetForeignEmote_Call) Run(run func(emoteID string, emoteText string)) *MockEmoteStore_LoadSetForeignEmote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmoteStore_LoadSetForeignEmote_Call) Return(emote1 emote.Emote) *MockEmoteStore_LoadSetForeignEmote_Call {
	_c.Call.Return(emote1)
	return _c
}

func (_c *MockEmoteStore_LoadSetForeignEmote_Call) RunAndReturn(run func(emoteID string, emoteText string) emote.Emote) *MockEmoteStore_LoadSetForeignEmote_Call {
	_c.Call.Return(run)
	return _c
}
