// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	ffz "github.com/julez-dev/chatuino/twitch/ffz"

	mock "github.com/stretchr/testify/mock"
)

// MockFFZEmoteFetcher is an autogenerated mock type for the FFZEmoteFetcher type
type MockFFZEmoteFetcher struct {
	mock.Mock
}

type MockFFZEmoteFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFFZEmoteFetcher) EXPECT() *MockFFZEmoteFetcher_Expecter {
	return &MockFFZEmoteFetcher_Expecter{mock: &_m.Mock}
}

// GetChannelEmotes provides a mock function with given fields: ctx, broadcaster
func (_m *MockFFZEmoteFetcher) GetChannelEmotes(ctx context.Context, broadcaster string) ([]ffz.Emote, error) {
	ret := _m.Called(ctx, broadcaster)

	if len(ret) == 0 {
		panic("no return value specified for GetChannelEmotes")
	}

	var r0 []ffz.Emote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]ffz.Emote, error)); ok {
		return rf(ctx, broadcaster)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []ffz.Emote); ok {
		r0 = rf(ctx, broadcaster)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ffz.Emote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, broadcaster)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFFZEmoteFetcher_GetChannelEmotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannelEmotes'
type MockFFZEmoteFetcher_GetChannelEmotes_Call struct {
	*mock.Call
}

// GetChannelEmotes is a helper method to define mock.On call
//   - ctx context.Context
//   - broadcaster string
func (_e *MockFFZEmoteFetcher_Expecter) GetChannelEmotes(ctx interface{}, broadcaster interface{}) *MockFFZEmoteFetcher_GetChannelEmotes_Call {
	return &MockFFZEmoteFetcher_GetChannelEmotes_Call{Call: _e.mock.On("GetChannelEmotes", ctx, broadcaster)}
}

func (_c *MockFFZEmoteFetcher_GetChannelEmotes_Call) Run(run func(ctx context.Context, broadcaster string)) *MockFFZEmoteFetcher_GetChannelEmotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFFZEmoteFetcher_GetChannelEmotes_Call) Return(_a0 []ffz.Emote, _a1 error) *MockFFZEmoteFetcher_GetChannelEmotes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFFZEmoteFetcher_GetChannelEmotes_Call) RunAndReturn(run func(context.Context, string) ([]ffz.Emote, error)) *MockFFZEmoteFetcher_GetChannelEmotes_Call {
	_c.Call.Return(run)
	return _c
}

// GetGlobalEmotes provides a mock function with given fields: _a0
func (_m *MockFFZEmoteFetcher) GetGlobalEmotes(_a0 context.Context) ([]ffz.Emote, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetGlobalEmotes")
	}

	var r0 []ffz.Emote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]ffz.Emote, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []ffz.Emote); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ffz.Emote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFFZEmoteFetcher_GetGlobalEmotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGlobalEmotes'
type MockFFZEmoteFetcher_GetGlobalEmotes_Call struct {
	*mock.Call
}

// GetGlobalEmotes is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockFFZEmoteFetcher_Expecter) GetGlobalEmotes(_a0 interface{}) *MockFFZEmoteFetcher_GetGlobalEmotes_Call {
	return &MockFFZEmoteFetcher_GetGlobalEmotes_Call{Call: _e.mock.On("GetGlobalEmotes", _a0)}
}

func (_c *MockFFZEmoteFetcher_GetGlobalEmotes_Call) Run(run func(_a0 context.Context)) *MockFFZEmoteFetcher_GetGlobalEmotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockFFZEmoteFetcher_GetGlobalEmotes_Call) Return(_a0 []ffz.Emote, _a1 error) *MockFFZEmoteFetcher_GetGlobalEmotes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFFZEmoteFetcher_GetGlobalEmotes_Call) RunAndReturn(run func(context.Context) ([]ffz.Emote, error)) *MockFFZEmoteFetcher_GetGlobalEmotes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFFZEmoteFetcher creates a new instance of MockFFZEmoteFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFFZEmoteFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFFZEmoteFetcher {
	mock := &MockFFZEmoteFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
