// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/julez-dev/chatuino/twitch/ffz"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFFZEmoteFetcher creates a new instance of MockFFZEmoteFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFFZEmoteFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFFZEmoteFetcher {
	mock := &MockFFZEmoteFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFFZEmoteFetcher is an autogenerated mock type for the FFZEmoteFetcher type
type MockFFZEmoteFetcher struct {
	mock.Mock
}

type MockFFZEmoteFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFFZEmoteFetcher) EXPECT() *MockFFZEmoteFetcher_Expecter {
	return &MockFFZEmoteFetcher_Expecter{mock: &_m.Mock}
}

// GetChannelEmotes provides a mock function for the type MockFFZEmoteFetcher
func (_mock *MockFFZEmoteFetcher) GetChannelEmotes(ctx context.Context, broadcaster string) ([]ffz.Emote, error) {
	ret := _mock.Called(ctx, broadcaster)

	if len(ret) == 0 {
		panic("no return value specified for GetChannelEmotes")
	}

	var r0 []ffz.Emote
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]ffz.Emote, error)); ok {
		return returnFunc(ctx, broadcaster)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []ffz.Emote); ok {
		r0 = returnFunc(ctx, broadcaster)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ffz.Emote)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, broadcaster)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFFZEmoteFetcher_GetChannelEmotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannelEmotes'
type MockFFZEmoteFetcher_GetChannelEmotes_Call struct {
	*mock.Call
}

// GetChannelEmotes is a helper method to define mock.On call
//   - ctx context.Context
//   - broadcaster string
func (_e *MockFFZEmoteFetcher_Expecter) GetChannelEmotes(ctx interface{}, broadcaster interface{}) *MockFFZEmoteFetcher_GetChannelEmotes_Call {
	return &MockFFZEmoteFetcher_GetChannelEmotes_Call{Call: _e.mock.On("GetChannelEmotes", ctx, broadcaster)}
}

func (_c *MockFFZEmoteFetcher_GetChannelEmotes_Call) Run(run func(ctx context.Context, broadcaster string)) *MockFFZEmoteFetcher_GetChannelEmotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFFZEmoteFetcher_GetChannelEmotes_Call) Return(emotes []ffz.Emote, err error) *MockFFZEmoteFetcher_GetChannelEmotes_Call {
	_c.Call.Return(emotes, err)
	return _c
}

func (_c *MockFFZEmoteFetcher_GetChannelEmotes_Call) RunAndReturn(run func(ctx context.Context, broadcaster string) ([]ffz.Emote, error)) *MockFFZEmoteFetcher_GetChannelEmotes_Call {
	_c.Call.Return(run)
	return _c
}

// GetGlobalEmotes provides a mock function for the type MockFFZEmoteFetcher
func (_mock *MockFFZEmoteFetcher) GetGlobalEmotes(context1 context.Context) ([]ffz.Emote, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetGlobalEmotes")
	}

	var r0 []ffz.Emote
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ffz.Emote, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ffz.Emote); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ffz.Emote)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFFZEmoteFetcher_GetGlobalEmotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGlobalEmotes'
type MockFFZEmoteFetcher_GetGlobalEmotes_Call struct {
	*mock.Call
}

// GetGlobalEmotes is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockFFZEmoteFetcher_Expecter) GetGlobalEmotes(context1 interface{}) *MockFFZEmoteFetcher_GetGlobalEmotes_Call {
	return &MockFFZEmoteFetcher_GetGlobalEmotes_Call{Call: _e.mock.On("GetGlobalEmotes", context1)}
}

func (_c *MockFFZEmoteFetcher_GetGlobalEmotes_Call) Run(run func(context1 context.Context)) *MockFFZEmoteFetcher_GetGlobalEmotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFFZEmoteFetcher_GetGlobalEmotes_Call) Return(emotes []ffz.Emote, err error) *MockFFZEmoteFetcher_GetGlobalEmotes_Call {
	_c.Call.Return(emotes, err)
	return _c
}

func (_c *MockFFZEmoteFetcher_GetGlobalEmotes_Call) RunAndReturn(run func(context1 context.Context) ([]ffz.Emote, error)) *MockFFZEmoteFetcher_GetGlobalEmotes_Call {
	_c.Call.Return(run)
	return _c
}
