// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/julez-dev/chatuino/twitch/twitchapi"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTwitchEmoteFetcher creates a new instance of MockTwitchEmoteFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTwitchEmoteFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTwitchEmoteFetcher {
	mock := &MockTwitchEmoteFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTwitchEmoteFetcher is an autogenerated mock type for the TwitchEmoteFetcher type
type MockTwitchEmoteFetcher struct {
	mock.Mock
}

type MockTwitchEmoteFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTwitchEmoteFetcher) EXPECT() *MockTwitchEmoteFetcher_Expecter {
	return &MockTwitchEmoteFetcher_Expecter{mock: &_m.Mock}
}

// GetChannelEmotes provides a mock function for the type MockTwitchEmoteFetcher
func (_mock *MockTwitchEmoteFetcher) GetChannelEmotes(ctx context.Context, broadcaster string) (twitchapi.EmoteResponse, error) {
	ret := _mock.Called(ctx, broadcaster)

	if len(ret) == 0 {
		panic("no return value specified for GetChannelEmotes")
	}

	var r0 twitchapi.EmoteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (twitchapi.EmoteResponse, error)); ok {
		return returnFunc(ctx, broadcaster)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) twitchapi.EmoteResponse); ok {
		r0 = returnFunc(ctx, broadcaster)
	} else {
		r0 = ret.Get(0).(twitchapi.EmoteResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, broadcaster)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTwitchEmoteFetcher_GetChannelEmotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannelEmotes'
type MockTwitchEmoteFetcher_GetChannelEmotes_Call struct {
	*mock.Call
}

// GetChannelEmotes is a helper method to define mock.On call
//   - ctx context.Context
//   - broadcaster string
func (_e *MockTwitchEmoteFetcher_Expecter) GetChannelEmotes(ctx interface{}, broadcaster interface{}) *MockTwitchEmoteFetcher_GetChannelEmotes_Call {
	return &MockTwitchEmoteFetcher_GetChannelEmotes_Call{Call: _e.mock.On("GetChannelEmotes", ctx, broadcaster)}
}

func (_c *MockTwitchEmoteFetcher_GetChannelEmotes_Call) Run(run func(ctx context.Context, broadcaster string)) *MockTwitchEmoteFetcher_GetChannelEmotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTwitchEmoteFetcher_GetChannelEmotes_Call) Return(emoteResponse twitchapi.EmoteResponse, err error) *MockTwitchEmoteFetcher_GetChannelEmotes_Call {
	_c.Call.Return(emoteResponse, err)
	return _c
}

func (_c *MockTwitchEmoteFetcher_GetChannelEmotes_Call) RunAndReturn(run func(ctx context.Context, broadcaster string) (twitchapi.EmoteResponse, error)) *MockTwitchEmoteFetcher_GetChannelEmotes_Call {
	_c.Call.Return(run)
	return _c
}

// GetGlobalEmotes provides a mock function for the type MockTwitchEmoteFetcher
func (_mock *MockTwitchEmoteFetcher) GetGlobalEmotes(context1 context.Context) (twitchapi.EmoteResponse, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetGlobalEmotes")
	}

	var r0 twitchapi.EmoteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (twitchapi.EmoteResponse, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) twitchapi.EmoteResponse); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(twitchapi.EmoteResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTwitchEmoteFetcher_GetGlobalEmotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGlobalEmotes'
type MockTwitchEmoteFetcher_GetGlobalEmotes_Call struct {
	*mock.Call
}

// GetGlobalEmotes is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockTwitchEmoteFetcher_Expecter) GetGlobalEmotes(context1 interface{}) *MockTwitchEmoteFetcher_GetGlobalEmotes_Call {
	return &MockTwitchEmoteFetcher_GetGlobalEmotes_Call{Call: _e.mock.On("GetGlobalEmotes", context1)}
}

func (_c *MockTwitchEmoteFetcher_GetGlobalEmotes_Call) Run(run func(context1 context.Context)) *MockTwitchEmoteFetcher_GetGlobalEmotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTwitchEmoteFetcher_GetGlobalEmotes_Call) Return(emoteResponse twitchapi.EmoteResponse, err error) *MockTwitchEmoteFetcher_GetGlobalEmotes_Call {
	_c.Call.Return(emoteResponse, err)
	return _c
}

func (_c *MockTwitchEmoteFetcher_GetGlobalEmotes_Call) RunAndReturn(run func(context1 context.Context) (twitchapi.EmoteResponse, error)) *MockTwitchEmoteFetcher_GetGlobalEmotes_Call {
	_c.Call.Return(run)
	return _c
}
