// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	twitchapi "github.com/julez-dev/chatuino/twitch/twitchapi"
)

// MockTwitchEmoteFetcher is an autogenerated mock type for the TwitchEmoteFetcher type
type MockTwitchEmoteFetcher struct {
	mock.Mock
}

type MockTwitchEmoteFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTwitchEmoteFetcher) EXPECT() *MockTwitchEmoteFetcher_Expecter {
	return &MockTwitchEmoteFetcher_Expecter{mock: &_m.Mock}
}

// GetChannelEmotes provides a mock function with given fields: ctx, broadcaster
func (_m *MockTwitchEmoteFetcher) GetChannelEmotes(ctx context.Context, broadcaster string) (twitchapi.EmoteResponse, error) {
	ret := _m.Called(ctx, broadcaster)

	if len(ret) == 0 {
		panic("no return value specified for GetChannelEmotes")
	}

	var r0 twitchapi.EmoteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (twitchapi.EmoteResponse, error)); ok {
		return rf(ctx, broadcaster)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) twitchapi.EmoteResponse); ok {
		r0 = rf(ctx, broadcaster)
	} else {
		r0 = ret.Get(0).(twitchapi.EmoteResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, broadcaster)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTwitchEmoteFetcher_GetChannelEmotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannelEmotes'
type MockTwitchEmoteFetcher_GetChannelEmotes_Call struct {
	*mock.Call
}

// GetChannelEmotes is a helper method to define mock.On call
//   - ctx context.Context
//   - broadcaster string
func (_e *MockTwitchEmoteFetcher_Expecter) GetChannelEmotes(ctx interface{}, broadcaster interface{}) *MockTwitchEmoteFetcher_GetChannelEmotes_Call {
	return &MockTwitchEmoteFetcher_GetChannelEmotes_Call{Call: _e.mock.On("GetChannelEmotes", ctx, broadcaster)}
}

func (_c *MockTwitchEmoteFetcher_GetChannelEmotes_Call) Run(run func(ctx context.Context, broadcaster string)) *MockTwitchEmoteFetcher_GetChannelEmotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTwitchEmoteFetcher_GetChannelEmotes_Call) Return(_a0 twitchapi.EmoteResponse, _a1 error) *MockTwitchEmoteFetcher_GetChannelEmotes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTwitchEmoteFetcher_GetChannelEmotes_Call) RunAndReturn(run func(context.Context, string) (twitchapi.EmoteResponse, error)) *MockTwitchEmoteFetcher_GetChannelEmotes_Call {
	_c.Call.Return(run)
	return _c
}

// GetGlobalEmotes provides a mock function with given fields: _a0
func (_m *MockTwitchEmoteFetcher) GetGlobalEmotes(_a0 context.Context) (twitchapi.EmoteResponse, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetGlobalEmotes")
	}

	var r0 twitchapi.EmoteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (twitchapi.EmoteResponse, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) twitchapi.EmoteResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(twitchapi.EmoteResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTwitchEmoteFetcher_GetGlobalEmotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGlobalEmotes'
type MockTwitchEmoteFetcher_GetGlobalEmotes_Call struct {
	*mock.Call
}

// GetGlobalEmotes is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockTwitchEmoteFetcher_Expecter) GetGlobalEmotes(_a0 interface{}) *MockTwitchEmoteFetcher_GetGlobalEmotes_Call {
	return &MockTwitchEmoteFetcher_GetGlobalEmotes_Call{Call: _e.mock.On("GetGlobalEmotes", _a0)}
}

func (_c *MockTwitchEmoteFetcher_GetGlobalEmotes_Call) Run(run func(_a0 context.Context)) *MockTwitchEmoteFetcher_GetGlobalEmotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTwitchEmoteFetcher_GetGlobalEmotes_Call) Return(_a0 twitchapi.EmoteResponse, _a1 error) *MockTwitchEmoteFetcher_GetGlobalEmotes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTwitchEmoteFetcher_GetGlobalEmotes_Call) RunAndReturn(run func(context.Context) (twitchapi.EmoteResponse, error)) *MockTwitchEmoteFetcher_GetGlobalEmotes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTwitchEmoteFetcher creates a new instance of MockTwitchEmoteFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTwitchEmoteFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTwitchEmoteFetcher {
	mock := &MockTwitchEmoteFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
